sudo: false
language: python
python:
    - '3.5.0b3'
# command to install dependencies
install: "pip install -U tox setuptools_scm"
# # command to run tests
env:
  matrix:
  - TESTENV=flakes
  - TESTENV=readme
  # matrix was trimmed to skip
  # some builds that are unnecessary/perceived redundant
  - TESTENV=py26-pytest24
  - TESTENV=py26-pytest25
  - TESTENV=py26-pytest26
  - TESTENV=py26-pytest27
  - TESTENV=py33-pytest27
  - TESTENV=py34-pytest24
  - TESTENV=py34-pytest25
  - TESTENV=py34-pytest26
  - TESTENV=py27-pytest24
  - TESTENV=py27-pytest25
  - TESTENV=py27-pytest26

  - TESTENV=py27-pytest27-pexpect
  - TESTENV=py34-pytest27-pexpect
  - TESTENV=py35-pytest27
  - TESTENV=pypy-pytest27

script: tox --recreate -e $TESTENV

notifications:
  irc:
    channels:
      - "chat.freenode.net#pytest"
    on_success: change
    on_failure: change
    skip_join: true
  email:
    - pytest-commit@python.org
